### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by nickclaw** [nickclaw/wtfu#3]

**Comment by nickclaw** [comment]
@austindg is going to get the barebones implementation up and running. @gulabry could you make some basic basic basic wireframes/layouts, then work on making the UI for the main activity over the weekend.

**Comment by gulabry** [comment]
Will do!

**Comment by gulabry** [comment]
I'm uploading wireframes & lo-fi layouts tonight. And I'll be implementing the main activity tonight as well!

**Comment by gulabry** [comment]
![img_3755](https://cloud.githubusercontent.com/assets/5587644/6481681/6af14998-c214-11e4-8c81-f7c6c6468d4d.JPG)
![img_3754](https://cloud.githubusercontent.com/assets/5587644/6481682/6af7bcce-c214-11e4-8a3d-97c3e9f97469.JPG)
![img_3753](https://cloud.githubusercontent.com/assets/5587644/6481680/6aebe50c-c214-11e4-8c63-b473c5af0468.JPG)

**Comment by gulabry** [comment]
Here's some very early custom UI implimentation!

**Comment by gulabry** [comment]
![screen shot 2015-03-05 at 1 03 59 am](https://cloud.githubusercontent.com/assets/5587644/6501952/8879d290-c2d3-11e4-8228-cdc0c5efceba.png)

**Comment by gulabry** [comment]
Long way to go but it's a good start on some UI stuff.
