### ISSUE TITLE
PendingIntents to AlarmManager, create BroadcastReceiver

### ISSUE THREAD

**Issue by ghost** [nickclaw/wtfu#8]
Set up PendingIntents for each alarm
Just log for now

Notes:
Fire every day, see if enabled that day

**Comment by nickclaw** [comment]
http://developer.android.com/reference/java/lang/System.html#currentTimeMillis()
http://developer.android.com/reference/java/util/TimeZone.html#getOffset(long)
http://developer.android.com/reference/android/app/AlarmManager.html#setRepeating(int, long, long, android.app.PendingIntent)
